spring.application.name=Exam_Room_Manager
spring.datasource.url=jdbc:postgresql://localhost:5432/exam_room_manager
spring.datasource.username=postgres
spring.datasource.password=evica123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
